### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by kostyrev**
because of ansible-lint

### CODE REVIEW

**Comment by kostyrev** [comment]
Please consider adding [pre-commit](http://pre-commit.com/) hooks like [this one](https://github.com/kostyrev/ansible-role-terraform/blob/master/.pre-commit-config.yaml).

**Comment by andrewrothstein** [comment]
great suggestion! thanks!

**Comment by andrewrothstein** [comment]
@kostyrev can you take a look at the precommit hooks I added with this [commit](https://github.com/andrewrothstein/ansible-unarchive-deps/commit/bf47197f7815ec3af64e5e2fcc2bbe01545cce30)? I had to use the --allow-missing-credentials flag with the detect-aws-credentials rule which seemed awkward. I noticed you didn't put that in your example.

**Comment by kostyrev** [comment]
Because I'm using 
> sha: v0.7.1

and you are 
> sha: v0.8.0

it seems that they've changed the behavior but I don't want to update to newer version 'cause I've no time right now.

**Pull request merged**
